### ISSUE TITLE
Package tries to upload .IPA instead of .APK

### ISSUE THREAD

**Issue by buchion** [wzieba/Firebase-Distribution-Github-Action#126]
Had an issue where Package tries to upload .IPA instead of APK

MY PIPELINE

```
name: Deploy Android to Firebase App Distribution on merge
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2

      - name: Install Dependencies
        run: flutter packages get

      - name: Decode Keystore
        id: write_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: app.keyStore
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Build
        run: flutter build apk
        env:
          ANDROID_KEYSTORE_PATH: ${{ steps.write_file.outputs.filePath }}
          ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: /home/runner/work/reponame/reponame/build/app/outputs/flutter-apk/app-release.apk
```
          

![Error ScreenShot](https://github.com/wzieba/Firebase-Distribution-Github-Action/assets/42196475/f113946e-11f6-4d4d-98a9-c11d8f6555c4)

  
![Error-A](https://github.com/wzieba/Firebase-Distribution-Github-Action/assets/42196475/f2da9311-0ced-4925-8bf8-7a6f8c47b6cd)
