### ISSUE TITLE
apk does not exist: verify that file points to a binary : Issue

### ISSUE THREAD

**Issue by laltukumar-ayla** [wzieba/Firebase-Distribution-Github-Action#130]
I am trying to distribute the release apk to Firebase. I am able to do it through the demo codebase. But when I am trying to upload it through actual getting the error "verify that file points to a binary". I am struggling to solve this from one week not able to fix it.
Please help me through fixing this.
My Job:

name: Deploy to Firebase

on:
  push:
    branches: [ Phase2_Development_Builds ]

jobs:
  build:
    name: Building and distributing app
    runs-on: ubuntu-latest
    env:
      SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Execute Gradle command - assembleRelease
        run: ./gradlew assembleRelease

      - name: Upload Artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: app/build/intermediates/apk/field/release/3.0.11(143).apk
          releaseNotes: "This is my new release notes lists"

**Comment by DarkAbhi** [comment]
Can confirm for same

```
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build Release APK
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: ./gradlew assembleRelease
      - name: send APK build on success
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            iku Earth Debug Build
            Author: ${{ github.actor }}
            Commit ID: ${{ github.sha }}

            Commit Message: ${{ github.event.head_commit.message }}

            View: https://github.com/Iku-earth/iku-earth-android/actions/runs/${{ github.run_id }}
          document: ./app/build/outputs/apk/release/*.apk
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{ secrets.FIREBASE_TEST_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN_CI }}
          groups: alpha
          file: /home/runner/work/iku-earth-android/iku-earth-android/app/build/outputs/apk/release/*.apk
     
```
