### ISSUE TITLE
Unable to parse JSON uploading apk

### ISSUE THREAD

**Issue by rvanderlinden** [wzieba/Firebase-Distribution-Github-Action#134]
Hi,

I'm trying to use this action in a reusable workflow to upload an apk to Firebase App Distribution. Unfortunately I keep getting an issue using `serviceCredentialsFileContent` that confuses me.

The error (if I set `debug: true` there is no additional output):
```
i  uploading binary...

Error: failed to upload release. Unable to parse JSON: SyntaxError: Unexpected token < in JSON at position 0
```

The action in use:
```
      - name: Deploy to Firebase App Distribution.
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          # The app ID in format 1:123:android:123abc123abc123 as taken from Firebase under Your Apps.
          appId: ${{ secrets.ANDROID_FIREBASE_APP_ID }}
          # The copied content of the private JSON key associated with the Service Account in the Google Cloud Console for this project, that has the Firebase App Distribution Admin role.
          serviceCredentialsFileContent: ${{ secrets.ANDROID_FIREBASE_SERVICE_ACCOUNT_JSON }}
          # Our test groups
          groups: ${{ vars.ANDROID_FIREBASE_APP_DISTRIBUTION_TEST_GROUPS }}
          # The artifact to upload, which definitely exists (tested and working for App Center distribution).
          file: "builds/${{ inputs.app-artifact-raw-filename }}"
```

Considering the error is related to parsing JSON and the `serviceCredentialsFileContent` is the only JSON submitted by me, I validated the service account, the key and the secrets. I have a similar setup for Play Store distribution (with a private JSON key) that *is* working so I'm unsure what I'm be doing wrong there. 

That brings me to my question: Is there any way I could get more information about the cause of the problem? I feel like the error `Unexpected token < in JSON at position 0` is not related to the `serviceCredentialsFileContent`, but I need more feedback to validate that. Any ideas how I can move forward? Thanks!

Full workflow:
```
on:
  workflow_call:

   # inputs redacted for brevity

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.github-environment }}
    steps:

      - name: Fetch project from remote.
        uses: actions/checkout@v4

      - name: Download artifact '${{ inputs.app-artifact-download-filename }}'.
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.app-artifact-download-filename }}
          path: ./builds

      - name: Deploy to Firebase App Distribution.
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.ANDROID_FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.ANDROID_FIREBASE_SERVICE_ACCOUNT_JSON }}
          groups: ${{ vars.ANDROID_FIREBASE_APP_DISTRIBUTION_TEST_GROUPS }}
          file: "./builds/${{ inputs.app-artifact-raw-filename }}"
```
