### ISSUE TITLE
failed to upload timed out after 300000ms

### ISSUE THREAD

**Issue by IzumiShaka-desu** [wzieba/Firebase-Distribution-Github-Action#135]
Hi,

I'm trying to use this action in a reusable workflow to upload an apk to Firebase App Distribution. Unfortunately I keep getting an issue after i make changes to my app(implement firebase core to the app) before the changes the apk successfully uploaded to firebase app distribution this error make me confused.

<img width="1098" alt="Screenshot 2024-05-17 at 14 11 46" src="https://github.com/wzieba/Firebase-Distribution-Github-Action/assets/65596335/8aeaab2e-c509-462c-8767-9b89df2a61b6">

my ci/cd pipelines:
```yaml
    - name: Prepare google-services.json
      id: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
          name: "google-services.json"
          json: ${{ secrets.GOOGLE_SERVICES_JSON_DEVELOPMENT }}
          dir: "android/app/"

    - name: Build release APK
      run: |
        flutter build apk --release \
        --dart-define=BASE_URL="${{ secrets.BASE_URL }}" \
        --dart-define=APP_VERSION="${{ secrets.APP_VERSION }}"
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk
    - name: Upload to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
          appId: ${{ secrets.APPID }} # Tambahkan FIREBASE_APP_ID di Secrets
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }} # Tambahkan FIREBASE_TOKEN di Secrets
          groups: testers
          debug: true
          file: build/app/outputs/flutter-apk/app-release.apk
```
