### ISSUE TITLE
How to get TESTING_URI ? 

### ISSUE THREAD

**Issue by faruk0344** [wzieba/Firebase-Distribution-Github-Action#141]
I am integrating firebase app Distribution system into my bitrise CI/CD
After apk uploaded to firebase app distribution i want to retrieve the TESTING_URI and add it to my env variable. 
So that I can send that download url via slack message. 

Any way to achieve it ?

**Comment by addyi** [comment]
@faruk0344 FYI this repo is for a github action to upload artifacts to firebase app distribution. This has nothing to do with bitrise.

If you actually care about the github action and not bitrise it works like this:

```yml
      - name: Upload artifact to Firebase App Distribution
        id: upload-artifact-to-firebase # this id is used in the next step to get the output
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIALS_FILE }}
          groups: testers
          file: file.apk

      - name: Print app distribution links
        run: |
          echo "FIREBASE_CONSOLE_URI: ${{ steps.upload-artifact-to-firebase.outputs.FIREBASE_CONSOLE_URI }}"
          echo "TESTING_URI: ${{ steps.upload-artifact-to-firebase.outputs.TESTING_URI }}"
          echo "BINARY_DOWNLOAD_URI: ${{ steps.upload-artifact-to-firebase.outputs.BINARY_DOWNLOAD_URI }}"
```
