### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bence-takacs-samlink** [wzieba/Firebase-Distribution-Github-Action#142]
Trying to upload an .ipa file from a macos-latest runner, and receive this: "Error: Container action is only supported on Linux"

There is a workaround: I can store the artifact and then retrieve it from a Linux conatiner and call Firebase-Distribution-Github-Action from there

```
jobs:
  build_with_signing:
    runs-on: macos-latest
    
  # build, compress, sign, etc
  
  - name: Store artifact
     uses: actions/upload-artifact@v4
        with:
          name: distribution-ios-feature
          path: ...
 
  publish-to-firebase:
    needs: build_with_signing
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment && inputs.environment || 'Omasp' }}
    steps:
    - name: Download the artifact
      uses: actions/download-artifact@v3
      with:
        name: distribution-ios-feature
        path: ...
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ...
        serviceCredentialsFileContent: ...
        file:  ...
```
