### ISSUE TITLE
Get file by pattern

### ISSUE THREAD

**Issue by Axrorxoja** [wzieba/Firebase-Distribution-Github-Action#18]
Hi there
Thank you for such amazing plugin
I want ask that can in my project build file name changed in every build
can I show file like so ?
`file: app/build/outputs/release/*.apk`

**Comment by wzieba** [comment]
hi @Axrorxoja, great to hear that this action is helpful for you! It's good idea to make this default behaviour to make plugin look for .apk name, I'm adding this to backlog.

There's a way though to achieve this by yourself, look at this snippet

```
 foo_bar_job:
    name: Build, test and upload to firebase
    runs-on: ubuntu-latest
    steps:
      # any steps before here
      - name: Get apk name
        id: apk-name
        run: |
          APK_NAME=$(echo app/build/outputs/release/*.apk)
          echo "::set-output name=APK_NAME::${APK_NAME}"
      - name: upload artifact to Firebase Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: <app id>
          token: <token>
          groups: <groups>
          file: ${{ steps.apk-name.outputs.APK_NAME }}
```

I hope this will help.
