### ISSUE TITLE
[Feature request]mac support

### ISSUE THREAD

**Issue by shinriyo** [wzieba/Firebase-Distribution-Github-Action#24]
```
Run wzieba/Firebase-Distribution-Github-Action@v1
  with:
    appId: app: "MY_ID"
    token: MY_TOKEN
    groups: testers
    file: build/ios/iphoneos/app.ipa
    debug: false
##[error]Container action is only supported on Linux
```

**Comment by wzieba** [comment]
Docker-based actions are not supported on MacOS, check the documentation for more: https://docs.github.com/en/actions/creating-actions/about-actions#docker-container-actions

I do not plan to make this action JavaScript-based.

**Comment by demchenkoalex** [comment]
If there are someone who like me didn't know how to upload an IPA at first, here's how you do it, based on this https://github.com/wzieba/Firebase-Distribution-Github-Action/issues/13#issuecomment-629468118

1. Build your IPA on macOS
2. Distribute your IPA using Ubuntu (make a different job based on a build one)

```yml
jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # build here
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: YourApp.ipa
          path: YourApp.ipa # Path to your IPA file will usually be root of the project (if you use Fastlane)

  distribute-ios:
    needs: build-ios # This is important
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: YourApp.ipa

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_IOS_APP_ID}}
          file: YourApp.ipa
          groups: testers
          token: ${{secrets.FIREBASE_TOKEN}}
```
