### ISSUE TITLE
Can somebody show me a screenshot of where i can find the right appId?

### ISSUE THREAD

**Issue by marcmarder** [wzieba/Firebase-Distribution-Github-Action#30]
CI stops on on the deploy action with the message "Error: set the --app option to a valid Firebase app id and try again".
I am not sure which appId is the right one in firebase so can someone point it out in a screenshot?

**Comment by wzieba** [comment]
Sure, I went to the gear icon (next to "Project Overview" label), and then on bottom, you should see something lint this:

<img width="722" alt="Screenshot 2020-09-25 at 10 03 50" src="https://user-images.githubusercontent.com/5845095/94242649-a9b81b80-ff16-11ea-8201-e10d769ca9b0.png">

**Comment by marcmarder** [comment]
Nice, thanks. Now i got a different error :/. 
It says: Error: failed to upload distribution. HTTP Error: 400, Unknown Error.
How can i find out, what went wrong?

**Comment by wzieba** [comment]
This looks very similar to this issue: https://github.com/wzieba/Firebase-Distribution-Github-Action/issues/29#issuecomment-696598543

I can't help with that as I can't reproduce it :(

Maybe you could find some help on [the official Firebase CLI Github repository](https://github.com/firebase/firebase-tools/issues) as this error is thrown by the Firebase CLI client.

It _might_ be also the issue with Firebase-Distribution-Github-Action, so if you'll find an answer to your issue I would appreciate reporting the solution in this issue. It would be great!

**Comment by alexsinger** [comment]
@marcmarder if you set the `debug`  option to `true`, do you see more output you can paste here? Also, for the app you're trying to distribute, did you press the "Get started" button in the Firebase App Distribution dashboard to initialize the app?

**Comment by wzieba** [comment]
@marcmarder were you able to fix your issue? If yes, could you please share what was the issue?

**Comment by marcmarder** [comment]
No i wasnt able to resolve the issue :(. @alexsinger where can i set the debug option to true?

**Comment by wzieba** [comment]
@marcmarder I think @alexsinger was writing about `debug` option in the action: https://github.com/wzieba/Firebase-Distribution-Github-Action#debug

So e.g. your workflow should look like
```yaml
(...)
- name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: testers
        file: app/build/outputs/apk/release/app-release-unsigned.apk
        debug: true # <---------
```

Also, have you pressed "Get started" on Firebase App Distribution like @alexsinger suggested? This might also be the issue.
