### ISSUE TITLE
Referencing GOOGLE_APPLICATION_CREDENTIALS serviceCredentialsFile path doesn't work

### ISSUE THREAD

**Issue by asc-adean** [wzieba/Firebase-Distribution-Github-Action#36]
I'm trying to use a Github Action secret to authenticate a Firebase push of an APK.  Here's the relevant tasks:

```
- name: Print GOOGLE_APPLICATION_CREDENTIALS_JSON to file
      shell: bash
      run: 'echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > "./firebase.json'
      env:
        GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}

    - name: look in the directory
      shell: bash
      run: |
        ls -l
        pwd
        cat ./firebase.json

    - name: Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
      with:
        appId: ${{ secrets.FIREBASE_ANDROID_DEV_APP_ID }}
        token: ${{ secrets.FIREBASE_TOKEN }}
        file: app/build/outputs/apk/debug/app-debug.apk 
        groups: dev
        serviceCredentialsFile: ./firebase.json

```

Output:

```
Run echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > "./firebase.json"
  echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > "./firebase.json"
  shell: /bin/bash --noprofile --norc -e -o pipefail ***0***
  env:
    JAVA_HOME_8.0.275_x64: /opt/hostedtoolcache/jdk/8.0.275/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.275/x64
    JAVA_HOME_8_0_275_X64: /opt/hostedtoolcache/jdk/8.0.275/x64
    GOOGLE_APPLICATION_CREDENTIALS_JSON: ***


Run ls -l
total 56
-rw-r--r-- 1 runner docker 1872 Nov 24 20:01 README.md
drwxr-xr-x 4 runner docker 4096 Nov 24 20:03 app
drwxr-xr-x 3 runner docker 4096 Nov 24 20:03 build
-rw-r--r-- 1 runner docker 2138 Nov 24 20:01 build.gradle
drwxr-xr-x 4 runner docker 4096 Nov 24 20:03 common
drwxr-xr-x 4 runner docker 4096 Nov 24 20:03 data
drwxr-xr-x 4 runner docker 4096 Nov 24 20:03 db
-rw-r--r-- 1 runner docker 2334 Nov 24 20:08 firebase.json
drwxr-xr-x 3 runner docker 4096 Nov 24 20:01 gradle
-rw-r--r-- 1 runner docker 1188 Nov 24 20:01 gradle.properties
-rwxr-xr-x 1 runner docker 5764 Nov 24 20:01 gradlew
-rw-r--r-- 1 runner docker 2942 Nov 24 20:01 gradlew.bat
-rw-r--r-- 1 runner docker   86 Nov 24 20:01 settings.gradle
/home/runner/work/proj-android/proj-android
***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
***

Run wzieba/Firebase-Distribution-Github-Action@v1.3.2
/usr/bin/docker run --name dfe4abb44dc88d32476cf13eee00_433322 --label 179394 --workdir /github/workspace --rm -e JAVA_HOME_8.0.275_x64 -e JAVA_HOME -e JAVA_HOME_8_0_275_X64 -e INPUT_APPID -e INPUT_TOKEN -e INPUT_FILE -e INPUT_GROUPS -e INPUT_SERVICECREDENTIALSFILE -e INPUT_RELEASENOTES -e INPUT_RELEASENOTESFILE -e INPUT_DEBUG -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/proj-android/proj-android":"/github/workspace" 179394:9678dfe4abb44dc88d32476cf13eee00
i  getting app details...

Error: failed to fetch app information. HTTP Error: 401, Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
```

This appears to be running inside of a Docker container, mounting the Github workspace directory. but it appears to not be picking up this file?  What is the solution here?  I've verified the credentials file is correct.

Thanks
