### ISSUE TITLE
pass variable in the path of file 

### ISSUE THREAD

**Issue by aymenbs2** [wzieba/Firebase-Distribution-Github-Action#48]
Please can I use github varible inside the apk file like xxx/xx/$GITHUB_SHA.apk

**Comment by mateuszkwiecinski** [comment]
@aymenbs2 Have you tried using github syntax? 

```
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        token: ${{ secrets.FIREBASE_TOKEN }}
        groups: testers
        file: app/build/outputs/apk/release/${{ github.sha }}.apk
```
I'm fairly sure it'll work
