### ISSUE TITLE
Error: failed to upload release. There's been an error parsing your app's info.plist. Ensure you are uploading a valid IPA and try again.

### ISSUE THREAD

**Issue by dev48india** [wzieba/Firebase-Distribution-Github-Action#58]
Having this error while running git action for IOS. 
(Error: failed to upload release. There's been an error parsing your app's info.plist. Ensure you are uploading a valid IPA and try again.)

Trying to distribute flutter app to firebase but only able to distribute apk file but for ios development job is giving me above error.
Following is attached code for .yml file used for git action command. 
Thanks in advance!!

```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#   build_android:
#     # This job will run on ubuntu virtual machine
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-java@v2
#         with:
#           distribution: 'zulu'
#           java-version: '11'
#       - uses: subosito/flutter-action@v2
#         with:
#           flutter-version: '2.5.3'
#       - run: flutter pub get
#       - run: flutter build apk
#       - run: flutter build appbundle
#       # Step to Submit the generated APK to Firebase App Distribution
#       - name: upload artifact to Firebase App Distribution
#         uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
#         with:
#           appId: ${{ secrets.FIREBASE_APP_ID }}
#           token: ${{ secrets.FIREBASE_TOKEN }}
#           groups: testerAndroid
#           file: build/app/outputs/flutter-apk/app-release.apk

  build_ios:
    name: Build Flutter (iOS)
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.3'
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios --release --no-codesign
      - run: cd /Users/runner/work/cicd/cicd/build/ios/iphoneos
      - run: ls
      - run: mkdir -p /Users/runner/work/cicd/cicd/build/ios/iphoneos/Payload
      - run: mv /Users/runner/work/cicd/cicd/build/ios/iphoneos/Runner.app /Users/runner/work/cicd/cicd/build/ios/iphoneos/Payload
      - run: zip -r /Users/runner/work/cicd/cicd/build/ios/iphoneos/Runner.ipa /Users/runner/work/cicd/cicd/build/ios/iphoneos/Payload
      - run: rm -rf /Users/runner/work/cicd/cicd/build/ios/iphoneos/Payload
      - name: Upload iPA
        uses: actions/upload-artifact@master
        with:
          name: ios-build
          path: build/ios/iphoneos
  beta_ios:
    name: Upload iOS Beta to Firebase App Distribution
    needs: [ build_ios ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: ios-build
      - name: Upload IPA
        uses: wzieba/Firebase-Distribution-Github-Action@v1.0.0
        with:
          appId: ${{ secrets.FIREBASE_IOS_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testerIos
          file: Runner.ipa
```
