### ISSUE TITLE
Release notes is empty on v1.3.3

### ISSUE THREAD

**Issue by dashika** [wzieba/Firebase-Distribution-Github-Action#67]
I updated the version from 1.3.2 to 1.3.3 and stopped filling release notes, it is empty. Can you help me with this, maybe in new version need some configuration?

**Comment by wzieba** [comment]
Thanks for the report - it shouldn't require any changed configuration so it's rather a bug in this action, sorry.

I'll try to work on this ASAP.

**Comment by wzieba** [comment]
But looking at changes between 1.3.2 and 1.3.3 I can't see a reason to break release notes. Maybe Firebase CLI changed their API, I have to check that.

Do you use `releaseNotes` or `releaseNotesFile` to pass release notes?

**Comment by dashika** [comment]
No, I don't use releaseNotes and releaseNotesFile.

**Comment by brian-pinwheel** [comment]
I have the same problem that release notes have shown up as empty.  I use the plugin for two builds.  The one where I specify `releaseNotes` is working as expected.  The one that I don't specify it and default to the commit hash code,  the release notes on Firebase are empty.  

I agree that it might be an issue with changing APIs somewhere.

**Comment by yoshuaandrean** [comment]
any updates on this?

**Comment by SergeiMikhailovskii** [comment]
@dashika @yoshuaandrean 

as a workaround, you can use this script:

```
  distribute:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: androidApp-debug.apk

      - name: Get latest commit
        id: vars
        run: echo ::set-output name=LATEST_COMMIT_MESSAGE::$(echo $(git log -1 --pretty=format:"%s"))

      - name: Upload artifact to FAD
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: androidApp-debug.apk
          releaseNotes: ${{ steps.vars.outputs.LATEST_COMMIT_MESSAGE }}
```

Here latest commit is fetched manually and saved into variable. then the release notes are taken from the variable
