### ISSUE TITLE
serviceCredentialsFile from secrets 

### ISSUE THREAD

**Issue by jemshit** [wzieba/Firebase-Distribution-Github-Action#72]
Hi,
could you guys provide a way to use `serviceAccount` from `secrets` instead of file? As an example [this action](https://github.com/r0adkll/upload-google-play) offers [it](https://github.com/r0adkll/upload-google-play/blob/060a2efa0e0e9c4305b19228cafd00898cd9d6f4/src/main.ts#L35)

**Comment by jemshit** [comment]
For now this can be used:
```yaml
- name: Decode AppDistribution ServiceAccount to JSON file
    id: decode-appdistribution-serviceaccount
    uses: timheuer/base64-to-file@master
    with:
      fileName: 'service-account.json'
      fileDir: './app_distribution/'
      encodedString: ${{ secrets.SERVICE_ACC_FIREBASE }}
```

then

`serviceCredentialsFile: ${{ steps.decode-appdistribution-serviceaccount.outputs.filePath }}`
