### ISSUE TITLE
Wildcard in file path?

### ISSUE THREAD

**Issue by roberto-corchero-jt** [wzieba/Firebase-Distribution-Github-Action#79]
Hi there!

I'm trying to upload the artifact using a wildcard in the file path, but I don't know if it's not allowed or I am making a mistake anywhere. Here's the workflow:

```yaml
- name: Upload artifact to Firebase App Distribution
  uses: wzieba/Firebase-Distribution-Github-Action@v1
  with:
    appId: ${{secrets.FIREBASE_APP_ID}}
    serviceCredentialsFile: presentation/firebase-app-distribution.json
    releaseNotesFile: CHANGELOG.md
    groups: android-team, product
    file: 'presentation/build/outputs/apk/*.apk'
```

I have checked that the apk file is in this path, but its name changes depending on some variables. I have tried with and without quotes.
