### ISSUE TITLE
Hi @mateuszkwiecinski We are also getting the same error but on the Ionic project. Can you help??

### ISSUE THREAD

**Issue by jmd9019** [wzieba/Firebase-Distribution-Github-Action#82]
Hi @mateuszkwiecinski We are also getting the same error but on the Ionic project. Can you help??

```
name: Build Android

on: [push, pull_request]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Capacitor
        run: npm install @capacitor/core

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install

      - name: Add Android platform
        run: |
          ionic capacitor add android
          ls

      - name: Build Android Dev APK
        run: ionic capacitor build android

      - name: Sync dependencies
        run: npx capacitor sync

      - name: Update plugins
        run: npx jetify

      - name: Build Android Release APK
        run: ionic capacitor build android --release --prod

      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Generate the Android Apk
        working-directory: ./android/
        run: |
          ./gradlew assembleRelease
          cd app/build/outputs/apk/release
          ls
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: via-driver-app
          file: app/build/outputs/apk/release/app-release-unsigned.apk 
```

![Screenshot (83)](https://user-images.githubusercontent.com/21059691/186138296-ae560c2b-480a-4951-bfc5-ec404297da56.png)

_Originally posted by @jmd9019 in https://github.com/wzieba/Firebase-Distribution-Github-Action/issues/51#issuecomment-1223886718_
