### ISSUE TITLE
Failed to authenticate, have you run firebase login?

### ISSUE THREAD

**Issue by CodemenschenAndroid** [wzieba/Firebase-Distribution-Github-Action#94]
I don't know why i am getting this error,

Here is my action file.

```
name: Deploy Application to Firebase App Distribution
on: [push, pull_request, workflow_dispatch]
jobs:
  run:
    runs-on: ubuntu-latest
    environment:
      name: qus
    steps:
      - uses: actions/checkout@v1
      - name: Upload artifact to Firebase Distribution using credential file content
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          groups: testers
          releaseNotesFile: README.md
          file: app/release/QusSports-Mobile-App-release.apk
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
```

![image](https://user-images.githubusercontent.com/60087122/207849132-591e1afb-a8ed-4c6d-8bd3-1b1a25be4ec0.png)
